---
title: "Rename T7.5"
date: last-modified
Type: "Rename"
Nomination: in prep.
categories: 
    - T7.5
    - Rename
---

The name of this ecosystem functional group in version 2.1 of the Global Ecosystem Typology is Derived semi-natural pastures and old fields. However, these ecosystems may be used as pastures or meadows, and may be better characterised as semi-natural grasslands to distinguish them clearly from cultivated pastures. As noted, different types of old fields can be associated with various agricultural ecosystem types and may display a range of different properties indicative of other functional groups (e.g. recruiting trees) depending on the initial state and successional pathway. We thus suggest resolution of these issue with the potential alternative name Derived semi-natural grasslands.

## Revision summary

Rename T7.5 Derived semi-natural grasslands

## Origin 

Agricultural ecosystems WG (Driver & Botts 2025)	

## Justification

Improve distinction from cultivated pastures

## Current status

Nomination in preparation